name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0
  pull_request:
    branches:
      - main

jobs:
  build-binaries-and-docker-image: # Renamed job for clarity
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        # Define target platforms for both Go build and Docker image
        include:
          - target: linux/amd64
            goos: linux
            goarch: amd64
          - target: linux/arm64
            goos: linux
            goarch: arm64
        # Add more platforms as needed:
        #  - target: linux/arm/v7
        #    goos: linux
        #    goarch: arm
        #    goarm: 7 # if GOARM is needed
        #  - target: windows/amd64
        #    goos: windows
        #    goarch: amd64

    steps:
      - name: Check Docker Hub Username
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "Error: DOCKERHUB_USERNAME secret is not set."
            exit 1
          elif [[ "${{ secrets.DOCKERHUB_USERNAME }}" == "***" ]]; then
            echo "Error: DOCKERHUB_USERNAME secret appears to be a placeholder '***'. Please set it correctly."
            exit 1
          fi
          echo "DOCKERHUB_USERNAME check passed."

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Specify your Go version

      - name: Build Go application for ${{ matrix.target }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          # GOARM: ${{ matrix.goarm }} # Uncomment if building for specific ARM versions like armv7
          CGO_ENABLED: 0
        run: |
          echo "Building for $GOOS/$GOARCH..."
          go build -ldflags="-s -w" -o dist/$GOOS-$GOARCH/ddns-dnspod .
          ls -l dist/$GOOS-$GOARCH/ # Verify binary exists

      - name: Set up QEMU
        if: runner.os == 'Linux' # QEMU is typically for cross-compilation on Linux runners
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # This must be a valid username
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ddns-dnspod # Replace with your Docker Hub username/repo
          # Add platform suffix to tags to distinguish images if building one image per platform
          # For a manifest list, you might not need platform-specific tags here if Docker Hub handles it.
          # This example assumes we are building a manifest list.
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=,suffix=,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image for ${{ matrix.target }}
        uses: docker/build-push-action@v5
        with:
          context: . # The whole repo, including the 'dist' dir with compiled binaries
          file: ./Dockerfile
          build-args: |
            TARGETOS=${{ matrix.goos }}
            TARGETARCH=${{ matrix.goarch }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: | # Create platform specific tags
            ${{ secrets.DOCKERHUB_USERNAME }}/ddns-dnspod:${{ steps.meta.outputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}
            ${{ secrets.DOCKERHUB_USERNAME }}/ddns-dnspod:latest-${{ matrix.goos }}-${{ matrix.goarch }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-manifest:
    needs: build-binaries-and-docker-image # Depends on the previous job (all matrix instances)
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
    steps:
      - name: Check Docker Hub Username
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "Error: DOCKERHUB_USERNAME secret is not set."
            exit 1
          elif [[ "${{ secrets.DOCKERHUB_USERNAME }}" == "***" ]]; then
            echo "Error: DOCKERHUB_USERNAME secret appears to be a placeholder '***'. Please set it correctly."
            exit 1
          fi
          echo "DOCKERHUB_USERNAME check passed for manifest job."

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for manifest
        id: meta_manifest
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ddns-dnspod
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Create and push manifest list
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          TAGS_TO_MANIFEST=""
          echo "${{ steps.meta_manifest.outputs.tags }}" | while IFS= read -r tag_base; do
            if [ -z "$tag_base" ]; then
              echo "Skipping empty base tag."
              continue
            fi
            echo "Processing base tag: $tag_base"
            
            # Define platform-specific tags based on the main tag_base
            # Ensure these match the tags pushed by the build-binaries-and-docker-image job
            # The build job pushes tags like: repo:version-os-arch and repo:latest-os-arch
            # The manifest should use the same base tag (e.g., repo:version or repo:latest)
            # and append the platform specific image names.

            # Construct platform image names. This assumes your build job tagged them as $tag_base-linux-amd64 etc.
            # The build job currently tags as:
            # ${{ secrets.DOCKERHUB_USERNAME }}/ddns-dnspod:${{ steps.meta.outputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}
            # ${{ secrets.DOCKERHUB_USERNAME }}/ddns-dnspod:latest-${{ matrix.goos }}-${{ matrix.goarch }}
            # So, if tag_base is "myuser/ddns-dnspod:v1.0.0", the platform images are
            # "myuser/ddns-dnspod:v1.0.0-linux-amd64", etc.

            PLATFORM_IMG_AMD64="${tag_base}-linux-amd64"
            PLATFORM_IMG_ARM64="${tag_base}-linux-arm64"

            echo "Creating manifest for $tag_base using:"
            echo "  $PLATFORM_IMG_AMD64"
            echo "  $PLATFORM_IMG_ARM64"

            docker manifest create --amend "$tag_base" \
              "$PLATFORM_IMG_AMD64" \
              "$PLATFORM_IMG_ARM64"
            # Add annotations if necessary, e.g., for ARM variants
            # docker manifest annotate "$tag_base" "$PLATFORM_IMG_ARM_V7" --os linux --arch arm --variant v7
            
            docker manifest push "$tag_base"
            TAGS_TO_MANIFEST="$TAGS_TO_MANIFEST $tag_base"
          done
          if [ -n "$TAGS_TO_MANIFEST" ]; then
            echo "Manifests created and pushed for tags:$TAGS_TO_MANIFEST"
          else
            echo "No tags processed for manifest creation."
          fi
